"""empty message

Revision ID: ea960e3ae131
Revises: 1d8676238874
Create Date: 2021-08-05 09:06:39.795248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea960e3ae131'
down_revision = '1d8676238874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grind_sessions', sa.Column('silver', sa.Integer(), nullable=False))
    op.add_column('grind_sessions', sa.Column('trash', sa.Integer(), nullable=False))
    op.drop_column('grind_sessions', 'hourly_silver')
    op.drop_column('grind_sessions', 'hourly_trash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grind_sessions', sa.Column('hourly_trash', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('grind_sessions', sa.Column('hourly_silver', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('grind_sessions', 'trash')
    op.drop_column('grind_sessions', 'silver')
    # ### end Alembic commands ###
