"""empty message

Revision ID: 1d8676238874
Revises: ffdc0a98111c
Create Date: 2021-07-30 09:15:02.956554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8676238874'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grind_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('char_class', sa.String(), nullable=False),
    sa.Column('ap', sa.Integer(), nullable=False),
    sa.Column('dp', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('hourly_silver', sa.Integer(), nullable=False),
    sa.Column('hourly_trash', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grind_sessions')
    # ### end Alembic commands ###
